micronaut:
  application:
    name: staffsergeant
  server:
    cors:
      enabled: true
    port: ${PORT:8080}
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
  security:
    enabled: true
    endpoints:
      login:
        enabled: false
      oauth:
        enabled: false
    token:
      jwt:
        enabled: true
        signatures:
          jwks:
            default:
              url: ${TOKEN_URL:xyz}'
    intercept-url-map:
      - access: isAnonymous()
        pattern: /swagger/**
      - access: isAnonymous()
        pattern: /swagger-ui/**
      - pattern: /**
        access:
          - isAuthenticated()


datasources:
  default:
    url: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
    schema-generate: NONE
    dialect: POSTGRES
    schema: staffsergeant

netty:
  default:
    allocator:
      max-order: 3

flyway:
  datasources:
    default:
      enabled: true
      default-schema: staffsergeant
      create-schemas: true
      schemas: staffsergeant
      clean-schema: true
