micronaut:
  application:
    name: staffseargant
  server:
    cors:
      enabled: true
    port: 8080
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: ${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}'

#datasources:
#  default:
#    url: jdbc:postgresql://localhost:5432/postgres
#    driverClassName: org.postgresql.Driver
#    username: postgres
#    password: postgres
#    schema-generate: create
#    dialect: POSTGRES
#    schema: staffseargant

netty:
  default:
    allocator:
      max-order: 3
